#!/usr/bin/env ruby

COMMAND_NAME = "lc"
SOURCE_FILE  = "main.go"
GENERATE_DIR = "gen"

SAMPLE_FILE = "sample.ltsv"
SAMPLES = [
  {fruits: "apple",  sports: "tennis",       movie: "matrix"},
  {fruits: "banana", sports: "table tennis", movie: "matrix"},
  {fruits: "berry",  sports: "baseball",     movie: "not interested"},
  {fruits: "apple",  sports: "snowboarding", movie: "oceans11"}
]

def sh command
  $stdout.print "Exec: "
  $stdout.puts command
  system command
end
  
if ARGV.first == "sample"
  SAMPLES.each do |items|
    File.open SAMPLE_FILE, "a" do |file|
      line = items.map{|k, v| "#{k}:#{v}" }.join "\t"
      file.puts line
    end
  end
else
  unless File.exists? GENERATE_DIR
    sh "mkdir #{GENERATE_DIR}"
  end

  [
    { :os => "linux",  :arch => "386"   },
    { :os => "linux",  :arch => "arm"   },
    { :os => "linux",  :arch => "amd64" },
    { :os => "darwin", :arch => "386"   },
    { :os => "darwin", :arch => "amd64" },
  ].each do |config|
    sh "env GOOS=#{config[:os]} GOARCH=#{config[:arch]} gom build -o #{GENERATE_DIR}/#{COMMAND_NAME}.#{config[:os]}.#{config[:arch]} #{SOURCE_FILE}"
  end
end
