#!/usr/bin/env ruby

if ARGV.first == "sample"
  SAMPLE_FILE = "sample.ltsv"
  SAMPLES = [
    {fruits: "apple",  sports: "tennis",       movie: "matrix"},
    {fruits: "banana", sports: "table tennis", movie: "matrix"},
    {fruits: "berry",  sports: "baseball",     movie: "not interested"},
    {fruits: "apple",  sports: "snowboarding", movie: "oceans11"}
  ]
  
  SAMPLES.each do |items|
    File.open SAMPLE_FILE, "a" do |file|
      line = items.map{|k, v| "#{k}:#{v}" }.join "\t"
      file.puts line
    end
  end

else
  system "go build -o lc main.go"
end
